/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PeriodsRouteImport } from './routes/periods'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StockRouteImport } from './routes/stock'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogIdRouteImport } from './routes/catalog.$id'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'
import { Route as DocumentsNewRouteImport } from './routes/documents.new'
import { Route as PrintIdRouteImport } from './routes/print.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronPeriodsRouteImport } from './routes/api/cron/periods'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodsRoute = PeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogIdRoute = CatalogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CatalogRoute,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsNewRoute = DocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DocumentsRoute,
} as any)
const PrintIdRoute = PrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPeriodsRoute = ApiCronPeriodsRouteImport.update({
  id: '/api/cron/periods',
  path: '/api/cron/periods',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/company': typeof CompanyRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/login': typeof LoginRoute
  '/money': typeof MoneyRoute
  '/partners': typeof PartnersRoute
  '/periods': typeof PeriodsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/stock': typeof StockRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/print/$id': typeof PrintIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/periods': typeof ApiCronPeriodsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/login': typeof LoginRoute
  '/money': typeof MoneyRoute
  '/partners': typeof PartnersRoute
  '/periods': typeof PeriodsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/stock': typeof StockRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/print/$id': typeof PrintIdRoute
  '/catalog': typeof CatalogIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/periods': typeof ApiCronPeriodsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/company': typeof CompanyRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/login': typeof LoginRoute
  '/money': typeof MoneyRoute
  '/partners': typeof PartnersRoute
  '/periods': typeof PeriodsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/stock': typeof StockRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/print/$id': typeof PrintIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/periods': typeof ApiCronPeriodsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/company'
    | '/documents'
    | '/login'
    | '/money'
    | '/partners'
    | '/periods'
    | '/reports'
    | '/staff'
    | '/stock'
    | '/catalog/$id'
    | '/documents/$id'
    | '/documents/new'
    | '/print/$id'
    | '/catalog/'
    | '/documents/'
    | '/api/auth/$'
    | '/api/cron/periods'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/login'
    | '/money'
    | '/partners'
    | '/periods'
    | '/reports'
    | '/staff'
    | '/stock'
    | '/catalog/$id'
    | '/documents/$id'
    | '/documents/new'
    | '/print/$id'
    | '/catalog'
    | '/documents'
    | '/api/auth/$'
    | '/api/cron/periods'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/company'
    | '/documents'
    | '/login'
    | '/money'
    | '/partners'
    | '/periods'
    | '/reports'
    | '/staff'
    | '/stock'
    | '/catalog/$id'
    | '/documents/$id'
    | '/documents/new'
    | '/print/$id'
    | '/catalog/'
    | '/documents/'
    | '/api/auth/$'
    | '/api/cron/periods'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MoneyRoute: typeof MoneyRoute
  PartnersRoute: typeof PartnersRoute
  PeriodsRoute: typeof PeriodsRoute
  ReportsRoute: typeof ReportsRoute
  StaffRoute: typeof StaffRoute
  StockRoute: typeof StockRoute
  PrintIdRoute: typeof PrintIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronPeriodsRoute: typeof ApiCronPeriodsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periods': {
      id: '/periods'
      path: '/periods'
      fullPath: '/periods'
      preLoaderRoute: typeof PeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/$id': {
      id: '/catalog/$id'
      path: '/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof CatalogIdRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/print/$id': {
      id: '/print/$id'
      path: '/print/$id'
      fullPath: '/print/$id'
      preLoaderRoute: typeof PrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/periods': {
      id: '/api/cron/periods'
      path: '/api/cron/periods'
      fullPath: '/api/cron/periods'
      preLoaderRoute: typeof ApiCronPeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CatalogRouteChildren {
  CatalogIdRoute: typeof CatalogIdRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogIdRoute: CatalogIdRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface DocumentsRouteChildren {
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsNewRoute: typeof DocumentsNewRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsNewRoute: DocumentsNewRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRouteWithChildren,
  CompanyRoute: CompanyRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  LoginRoute: LoginRoute,
  MoneyRoute: MoneyRoute,
  PartnersRoute: PartnersRoute,
  PeriodsRoute: PeriodsRoute,
  ReportsRoute: ReportsRoute,
  StaffRoute: StaffRoute,
  StockRoute: StockRoute,
  PrintIdRoute: PrintIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronPeriodsRoute: ApiCronPeriodsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
