/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StockRouteImport } from './routes/stock'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogIdRouteImport } from './routes/catalog.$id'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'
import { Route as DocumentsNewRouteImport } from './routes/documents.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogIdRoute = CatalogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CatalogRoute,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsNewRoute = DocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/reports': typeof ReportsRoute
  '/stock': typeof StockRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/catalog/': typeof CatalogIndexRoute
  '/documents/': typeof DocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/partners': typeof PartnersRoute
  '/reports': typeof ReportsRoute
  '/stock': typeof StockRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/catalog': typeof CatalogIndexRoute
  '/documents': typeof DocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/reports': typeof ReportsRoute
  '/stock': typeof StockRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/catalog/': typeof CatalogIndexRoute
  '/documents/': typeof DocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/documents'
    | '/partners'
    | '/reports'
    | '/stock'
    | '/catalog/$id'
    | '/documents/$id'
    | '/documents/new'
    | '/catalog/'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/partners'
    | '/reports'
    | '/stock'
    | '/catalog/$id'
    | '/documents/$id'
    | '/documents/new'
    | '/catalog'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/documents'
    | '/partners'
    | '/reports'
    | '/stock'
    | '/catalog/$id'
    | '/documents/$id'
    | '/documents/new'
    | '/catalog/'
    | '/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  DocumentsRoute: typeof DocumentsRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  ReportsRoute: typeof ReportsRoute
  StockRoute: typeof StockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/$id': {
      id: '/catalog/$id'
      path: '/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof CatalogIdRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof DocumentsRoute
    }
  }
}

interface CatalogRouteChildren {
  CatalogIdRoute: typeof CatalogIdRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogIdRoute: CatalogIdRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface DocumentsRouteChildren {
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsNewRoute: typeof DocumentsNewRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsNewRoute: DocumentsNewRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRouteWithChildren,
  DocumentsRoute: DocumentsRouteWithChildren,
  PartnersRoute: PartnersRoute,
  ReportsRoute: ReportsRoute,
  StockRoute: StockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
